### ISSUE TITLE
Unable to initialize OpenGL

### ISSUE THREAD

**Issue by dmd** [pauldmccarthy/fsleyes#108]
On a basically brand new install of RHEL 8, in a completely brand new install of fsl 6.0.6.4:

```
$ fsleyes
   ERROR              main.py  592: initialise      - Unable to initialise OpenGL!
Traceback (most recent call last):
  File "/cm/shared/apps/fsl-6.0.6.4/lib/python3.10/site-packages/fsleyes/gl/__init__.py", line 884, in __createWXGLCanvas
    self.__canvas = wxgl.GLCanvas(self.__parent, **attrs)
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1668091581272/work/ext/wxWidgets/src/unix/glx11.cpp(626) in InitVisual(): Failed to get a XVisualInfo for the requested attributes.
During handling of the above exception, another exception occurred:
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1668091581272/work/ext/wxWidgets/src/unix/glx11.cpp(626) in InitVisual(): Failed to get a XVisualInfo for the requested attributes.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/cm/shared/apps/fsl-6.0.6.4/lib/python3.10/site-packages/fsleyes/main.py", line 588, in initialise
    fslgl.getGLContext(ready=realCallback,
  File "/cm/shared/apps/fsl-6.0.6.4/lib/python3.10/site-packages/fsleyes/gl/__init__.py", line 553, in getGLContext
    thismod._glContext = GLContext(**kwargs)
  File "/cm/shared/apps/fsl-6.0.6.4/lib/python3.10/site-packages/fsleyes/gl/__init__.py", line 732, in __init__
    self.__createWXGLCanvas()
  File "/cm/shared/apps/fsl-6.0.6.4/lib/python3.10/site-packages/fsleyes/gl/__init__.py", line 893, in __createWXGLCanvas
    self.__canvas = wxgl.GLCanvas(self.__parent)
SystemError: <class 'wx._glcanvas.GLCanvas'> returned a result with an exception set
```

I assume this is something obvious, but I don’t know what it is.

**Comment by dmd** [comment]
Oh sorry I forgot I'd opened this. No, they don't :)

**Comment by dmd** [comment]
Although, this is weird - on my other (production) system, glxgears returns "Error: couldn't get an RGB, Double-buffered visual" *but* fsleyes works fine!
