### ISSUE TITLE
fsleyes - ventura error

### ISSUE THREAD

**Issue by nmskhan** [pauldmccarthy/fsleyes#116]
Hi 
I updated my Mac to Ventura 13.4 recently and I noticed that there was an error in launching fsl from the terminal as well as the icon, fsl popped up and says loading, but nothing happened for several hours. I had to forcefully quit. However, all fsl command functions (math and other functions)  work in the terminal.  Any suggestions are appreciated

**These are the errors that appeared in the terminal during the launch**

 WARNING          __init__.py  628: create          - GLContext callback function raised ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A): tried: 'OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSOpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/lib-dynload/../../OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/python.app/Contents/MacOS/../lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/python.app/Contents/MacOS/../../../lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache)", 'OpenGL', None)
Traceback (most recent call last):
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 38, in GL
    mode=ctypes.RTLD_GLOBAL
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ("dlopen(OpenGL, 0x000A): tried: 'OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSOpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/lib-dynload/../../OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/python.app/Contents/MacOS/../lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/python.app/Contents/MacOS/../../../lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache)", 'OpenGL', None)

During the handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 622, in create
    ready()
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/fsleyes/main.py", line 537, in realCallback
    fslgl.bootstrap(namespace.glversion)
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 301, in bootstrap
    import OpenGL.GL         as gl
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A): tried: 'OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSOpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/lib-dynload/../../OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/fsl/fslpython/envs/fslpython/lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/python.app/Contents/MacOS/../lib/OpenGL' (no such file), '/usr/local/fsl/fslpython/envs/fslpython/python.app/Contents/MacOS/../../../lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache)", 'OpenGL', None)

**Comment by pauldmccarthy** [comment]
Hi @nmskhan, it looks like your OS update has broken the `$FSLDIR/fslpython/` conda environment, so I'd recommend re-installing FSL.

**Comment by nmskhan** [comment]
Thank you ! I will reinstall it.
