### ISSUE TITLE
KeyError: 'fsleyes_pink'

### ISSUE THREAD

**Issue by nmossazg12** [pauldmccarthy/fsleyes#120]
HI, 

We installed fsleyes by installing the fsl in both mac and windows. When we try to open fsleyes, we receive the following error. Furthermore, even if fsleyes opens, the interface misses a lot of the features such as brightness, contrast (screenshot included below). I was wondering if you could help me figure out the issue. 

Thank you
OS = Windows 10
Installed the FSL using Windows Linux Subsystem (Ubuntu 20.04)
`

ValueError: 'fsleyes_pink' is not in list
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes_props/callqueue.py", line 222, in __call
    call.func(*call.args, **call.kwargs)
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes/controls/overlaydisplaytoolbar.py", line 240, in __selectedOverlayChanged
    self.__showTools(overlay)
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes/controls/overlaydisplaytoolbar.py", line 181, in __showTools
    optsTools, optsNav = makeFunc(opts)
                         ^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes/controls/overlaydisplaytoolbar.py", line 351, in __makeVolumeOptsTools
    cmapWidget       = props.buildGUI(cmapPanel, opts, cmapSpec)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes_props/build.py", line 1018, in buildGUI
    mainPanel = _create(parentObj, view, hasProps, propGui)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes_props/build.py", line 780, in _create
    guiObject = createFunc(parent, viewItem, hasProps, propGui)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes_props/build.py", line 474, in _createWidget
    widget = widgets.makeWidget(    parent,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes_props/widgets.py", line 782, in makeWidget
    return makeFunc(parent, hasProps, propObj, propVal, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes_props/widgets.py", line 664, in _ColourMap
    cmapsChanged()
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes_props/widgets.py", line 636, in cmapsChanged
    name = labels(cmap.name)
           ^^^^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes/colourmaps.py", line 745, in getColourMapLabel
    return _caseInsensitiveLookup(_cmaps, key).name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmossazg/fsl/lib/python3.11/site-packages/fsleyes/colourmaps.py", line 1265, in _caseInsensitiveLookup
    else:                   raise  KeyError(k)
                            ^^^^^^^^^^^^^^^^^^
KeyError: 'fsleyes_pink'

`
![fdd](https://github.com/pauldmccarthy/fsleyes/assets/94238160/fa2286ce-c40c-4a82-ad5a-9e069d62b004)

**Comment by pauldmccarthy** [comment]
Hi @nmossazg12, you should be able to resolve this by downgrading your version of matplotlib with a command such as:
```
$FSLDIR/bin/mamba install -n base matplotlib-base="3.7"
```

The matplotlib colormaps API has changed in the last two minor versions ([3.7](https://github.com/matplotlib/matplotlib/pull/23668) and [3.8](https://github.com/matplotlib/matplotlib/pull/25479)), and has broken FSLeyes on both occasions. I have updated the FSLeyes code base so that this will hopefully not happen again, but have not yet had time to release a new version of FSLeyes - I'll hopefully have  time next week.

**Comment by nmossazg12** [comment]
Hi @pauldmccarthy, Downgrading to matplotlib 3.7 did the trick. 

Thanks
