### ISSUE TITLE
Unable to open FSLeyes on windows 10

### ISSUE THREAD

**Issue by sanosenx86** [pauldmccarthy/fsleyes#123]
Hi, I have installed FSLeyes via conda, but I am unable to open it. Could you please help me with this problem?

Logging
```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
 WARNING          __init__.py  756: create          - GLContext callback function raised NullFunctionError: Attempt to call an undefined function glGenFramebuffers, check for bool(glGenFramebuffers) before calling
Traceback (most recent call last):
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\gl\__init__.py", line 753, in create
    ready()
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\main.py", line 583, in realCallback
    callback()
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\main.py", line 370, in buildGui
    frame = makeFrame(namespace[0],
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\main.py", line 795, in makeFrame
    frame = fsleyesframe.FSLeyesFrame(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\frame.py", line 311, in __init__
    self.__restoreState(restore)
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\frame.py", line 1460, in __restoreState
    layouts.loadLayout(self, 'default')
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\layouts.py", line 200, in loadLayout
    applyLayout(frame, name, layout, **kwargs)
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\layouts.py", line 239, in applyLayout
    frame.addViewPanel(vp, defaultLayout=False)
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\frame.py", line 511, in addViewPanel
    panel = panelCls(self.__mainPanel, self.__overlayList, childDC, self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\views\orthopanel.py", line 206, in __init__
    self.__xcanvas = slicecanvas.WXGLSliceCanvas(contentPanel,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\gl\wxglslicecanvas.py", line 45, in __init__
    fslgl.WXGLCanvasTarget .__init__(self)
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\gl\__init__.py", line 1247, in __init__
    self.__fbo = rendertexture.RenderTexture(f'fbo_{id(self)}', 'c')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\gl\textures\rendertexture.py", line 121, in __init__
    self.__frameBuffer      = glexts.glGenFramebuffers(1)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\OpenGL\wrapper.py", line 671, in wrapperCall
    result = wrappedOperation( *cArguments )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenFramebuffers, check for bool(glGenFramebuffers) before calling
--- Logging error ---
 WARNING              idle.py  578: __idleLoop      - Idle task __bgfgColourChanged crashed - AttributeError: 'OrthoPanel' object has no attribute '_OrthoPanel__xcanvas'
Traceback (most recent call last):
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsl\utils\idle.py", line 576, in __idleLoop
    task.task(*task.args, **task.kwargs)
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\views\canvaspanel.py", line 590, in __bgfgColourChanged
    canvases  = self.getGLCanvases()
                ^^^^^^^^^^^^^^^^^^^^
  File "D:\miniforge3\envs\neuroimg\Lib\site-packages\fsleyes\views\orthopanel.py", line 518, in getGLCanvases
    canvas = [self.__xcanvas, self.__ycanvas, self.__zcanvas]
              ^^^^^^^^^^^^^^
AttributeError: 'OrthoPanel' object has no attribute '_OrthoPanel__xcanvas'
--- Logging error ---
```

**Comment by pauldmccarthy** [comment]
Sorry, I don't have access to a Windows computer, so can't really help. But it looks like you don't have any OpenGL renderer installed.

**Comment by AzyshFotbnxe** [comment]
Hi, I doublechecked that I have OpenGL 4.6 installed, and OpenGL library successfully read out the version. I also reinstalled fsleyes and graphic cards driver, but the problem is still there. Could you please check if anything wrong happened?

**Comment by pauldmccarthy** [comment]
Does `glxgears` work when run from within your WSL system? What does `glxinfo` report?
