### ISSUE TITLE
use matplotlib color maps

### ISSUE THREAD

**Issue by burdinskid13** [pauldmccarthy/fsleyes#127]
Hi there! I have been trying to use fsleyes render together with two matplotlib color maps that I'd like to use. I cannot figure out how to properly add them to this command to make it work unfortunately. Any help would be much appreciated! Specifically, I'd like to use the Greens and Purples colormaps in the places of $cmap_pos and $cmap_neg. See my code below, which works fine with the built-in color maps in the places of $cmap_pos and $cmap_neg. Thank you!

```
! fsleyes render --neuroOrientation --outfile $Out -sz  500 500 \
       --selectedOverlay 1 --scene ortho --worldLoc 0 0 0 \
       --zcentre  0  0 --showLocation no \
       --layout horizontal --hidex --hidey --hideCursor \
       --showColourBar --colourBarLocation right --colourBarLabelSide top-left --colourBarSize 85.0 --labelSize 14 \
       $Anat --overlayType volume  \
       $Effect --name "" --overlayType volume --modulateImage $Stat --cmap $cmap_pos --negativeCmap $cmap_neg --useNegativeCmap --displayRange 0.0 13 --modulateRange 0.0 7.0 --modulateAlpha \
       $Stat --overlayType mask --alpha 100.0 --threshold -$Threshold $Threshold --outline --maskColour 0 0 0

```

**Comment by pauldmccarthy** [comment]
Hi @burdinskid13, this works fine for me - what version o FSLeyes are you using?

```
fsleyes  render -of out.png  \
  ~/fsl_course_data/rest/ICA/groupICA15/melodic_IC \
  -cm Greens -nc Purples -dr 0 5
```
![out](https://github.com/pauldmccarthy/fsleyes/assets/236128/e9e466f0-6f1b-4a0d-9b2c-27759e5c6f21)

**Comment by pauldmccarthy** [comment]
And what version of matplotlib do you have installed?

What happens when you try to use a built-in colour map? Do you get any error messages? Is an output file produced?

**Comment by burdinskid13** [comment]
I currently have matplotlib: 3.7.1. I don't get any error messages when I use the built-in color maps from fsleyes and the output is produced correctly

**Comment by burdinskid13** [comment]
Sorry, I thought you meant built-in to fsleyes. Here is the error message when I use `--cmap Greens`:

`Traceback (most recent call last):
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/colourmaps.py", line 1262, in _caseInsensitiveLookup
    idx = lKeys.index(k.lower())
ValueError: 'greens' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/om2/user/dclb/.miniconda/envs/fsleyes/bin/fsleyes", line 10, in <module>
    sys.exit(main())
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/filtermain.py", line 216, in main
    result = fm.main(args)
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/main.py", line 234, in main
    render.main(args[1:])
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/render.py", line 93, in main
    bitmap, bg = render(
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/render.py", line 423, in render
    cbarBmp = buildColourBarBitmap(overlayList,
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/render.py", line 676, in buildColourBarBitmap
    cbarBmp = cb.colourBar(width, height)
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/controls/colourbar.py", line 304, in colourBar
    cmap = fslcm.getColourMapMplKey(cmap.name)
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/colourmaps.py", line 740, in getColourMapMplKey
    return _caseInsensitiveLookup(_cmaps, key).mplkey
  File "/om2/user/dclb/.miniconda/envs/fsleyes/lib/python3.9/site-packages/fsleyes/colourmaps.py", line 1265, in _caseInsensitiveLookup
    else:                   raise  KeyError(k)
KeyError: 'Greens'`
