### ISSUE TITLE
problem about "lookuptablepanel.py"

### ISSUE THREAD

**Issue by Stonlee** [pauldmccarthy/fsleyes#129]
Hello, I meet the python problem when I inport the table of brain atlas name when loading LUT.  I dont know whther this is the version problem of my fsleyes or the source code. Thanks.

Traceback (most recent call last):
  File "/fslpython2/lib/python3.9/site-packages/fsleyes/plugins/controls/lookuptablepanel.py", line 527, in __onLoadLut
    lutKey, lutName = promptForLutName(lutName)
  File "/fslpython2/lib/python3.9/site-packages/fsleyes/plugins/controls/lookuptablepanel.py", line 713, in promptForLutName
    lutKey  = fslcmaps.makeValidMapKey(lutName)
AttributeError: module 'fsleyes.colourmaps' has no attribute 'makeValidMapKey'.

**Comment by pauldmccarthy** [comment]
Hi @Stonlee, this looks like a bug which was introduced about a month ago. I'll fix it for the next FSLeyes version
