### ISSUE TITLE
fsleyes render command line error

### ISSUE THREAD

**Issue by Arshitha** [pauldmccarthy/fsleyes#135]
Hi there, 

 I'm trying to generate 3d renders using fsleyes command line tools but I'm getting the "unrecognized arguments" error. I've used the same command in my workflow previously and it used work without any issues a few months back. 

**Command:** 

```bash
fsleyes render --scene 3d --outfile \
/data/BIDS_test/derivatives/defacing_outputs/sub-01/ses-01/T1w/defaced_render_01.png \
/data/BIDS_test/derivatives/defacing_outputs/sub-01/ses-01/T1w/defaced.nii.gz \
--cameraRotation -45 5 10 --displayRange 20 250 \
--interpolation spline --cmap render1 --blendFactor 0.3 \
-r 100 --numSteps 500
```

**Error:** 

```bash
unrecognized arguments: /data/BIDS_test/derivatives/defacing_outputs/sub-01/ses-01/T1w/defaced.nii.gz --displayRange 20 250 --interpolation spline --cmap render1 --blendFactor 0.3 -r 100 --numSteps 500
FSLeyes render version 1.10.3
Usage: render [options] -of outfile file [displayOpts] file [displayOpts] ...
```

**FSLeyes versions:** 

I've tried the above command with v1.7 and v1.10.3 with the same result.

I've verified that files are present at the file paths specified. I'd appreciate any help in resolving this issue. Thank you!

Best,
Arsh

**Comment by pauldmccarthy** [comment]
Hi @Arshitha,

All "scene" options must be specified before "overlay" options - in this case, you are specifying the `--cameraRotation` option after you have specified overlay files. Move that option (and its arguments) before your overlays, and the command should work.

**Comment by Arshitha** [comment]
Thank you @pauldmccarthy ! That resolved the unrecognized arguments issue. But I received the following error when I tried the command in a conda environment with FSLeyes render version 1.10.3  

Corrected command that I ran:
```bash
fsleyes render --scene 3d --cameraRotation -45 5 10 --outfile defaced_render_00.png defaced.nii.gz --displayRange 20 250 --interpolation spline --cmap render1 --blendFactor 0.3 -r 100 --numSteps 500
```

Error with the fsleyes v1.10.3 conda installation:

```bash
(fsleyes)[arshithab@cn2877 T1w]$ fsleyes render --scene 3d --cameraRotation -45 5 10 --outfile defaced_render_00.png defaced.nii.gz --displayRange 20 250 --interpolation spline --cmap render1 --blendFactor 0.3 -r 100 --numSteps 500
Traceback (most recent call last):                                                                                                                                                                                                                            
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/bin/fsleyes", line 10, in <module>                                                                                                                                                               
    sys.exit(main())                                                                                                                                                                                                                                          
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/lib/python3.8/site-packages/fsleyes/filtermain.py", line 218, in main                                                                                                                            
    result = fm.main(args)                                                                                                                                                                                                                                    
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/lib/python3.8/site-packages/fsleyes/main.py", line 234, in main                                                                                                                                  
    render.main(args[1:])                                                                                                                                                                                                                                     
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/lib/python3.8/site-packages/fsleyes/render.py", line 69, in main                                                                                                                                 
    fslgl.getGLContext(offscreen=True,                                                                                                                                                                                                                        
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/lib/python3.8/site-packages/fsleyes/gl/__init__.py", line 553, in getGLContext                                                                                                                   
    thismod._glContext = GLContext(**kwargs)                                                                                                                                                                                                                  
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/lib/python3.8/site-packages/fsleyes/gl/__init__.py", line 704, in __init__                                                                                                                       
    self.__createOSMesaContext()                                                                                                                                                                                                                              
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/lib/python3.8/site-packages/fsleyes/gl/__init__.py", line 1009, in __createOSMesaContext                                                                                                         
    context = osmesa.OSMesaCreateContextExt(                                                                                                                                                                                                                  
  File "/data/NIMH_scratch/arshithab/miniconda3/envs/fsleyes/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 423, in __call__                                                                                                              
    raise error.NullFunctionError(                                                                                                                                                                                                                            
OpenGL.error.NullFunctionError: Attempt to call an undefined function OSMesaCreateContextExt, check for bool(OSMesaCreateContextExt) before calling                                                                                                           
```

I tried running the same command after setting `PYOPENGL_PLATFORM="osmesa"` (based on instructions [here](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/install.html#install-from-conda-forge-recommended)) but got the same error as above. 


However, with HPC's FSL 6.0.5 installation that comes with **FSLeyes render version 1.4.6**, the command worked successfully.

**Comment by Arshitha** [comment]
**Update:** I was able to get the command running with the conda environment with FSLeyes v1.10.3 by unsetting `PYOPENGL_PLATFORM="osmesa"` environment variable. 

Apologies for the false alert. Closing this issue now, thank you!
