### ISSUE TITLE
"Show command line for scene" returns a TypeError when a copy of a volume is open

### ISSUE THREAD

**Issue by smoia** [pauldmccarthy/fsleyes#63]
Hello,
I was trying to get the command line equivalent of a scene I set up, but instead got this error in the terminal (and no command line box):
```
fsleyes

  cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
/home/nemo/.local/lib/python3.8/site-packages/wx/core.py:2224: Warning: invalid (NULL) pointer instance
  rv = wx.PyApp.MainLoop(self)
/home/nemo/.local/lib/python3.8/site-packages/wx/core.py:2224: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  rv = wx.PyApp.MainLoop(self)
/home/nemo/.local/lib/python3.8/site-packages/wx/core.py:2224: Warning: g_signal_handler_block: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  rv = wx.PyApp.MainLoop(self)
/home/nemo/.local/lib/python3.8/site-packages/wx/core.py:2224: Warning: g_signal_handler_unblock: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  rv = wx.PyApp.MainLoop(self)

  dc.DrawText(line, x, y)
Traceback (most recent call last):
  File "/home/nemo/.local/lib/python3.8/site-packages/fsleyes/frame.py", line 829, in wrapper
    self.__onViewPanelMenuItem(vp, aname, sc, **kwargs)
  File "/home/nemo/.local/lib/python3.8/site-packages/fsleyes/frame.py", line 997, in __onViewPanelMenuItem
    func()
  File "/home/nemo/.local/lib/python3.8/site-packages/fsleyes/actions/base.py", line 172, in __call__
    return self.__func(*args, **kwargs)
  File "/home/nemo/.local/lib/python3.8/site-packages/fsleyes/views/canvaspanel.py", line 392, in showCommandLineArgs
    ShowCommandLineAction(self.overlayList, self.displayCtx, self)()
  File "/home/nemo/.local/lib/python3.8/site-packages/fsleyes/actions/base.py", line 172, in __call__
    return self.__func(*args, **kwargs)
  File "/home/nemo/.local/lib/python3.8/site-packages/fsleyes/actions/showcommandline.py", line 50, in __showCommandLineArgs
    showCommandLineArgs(self.overlayList, self.displayCtx, self.__panel)
  File "/home/nemo/.local/lib/python3.8/site-packages/fsleyes/actions/showcommandline.py", line 67, in showCommandLineArgs
    text=' '.join(args),
TypeError: sequence item 49: expected str instance, NoneType found


```
It happens only if I create a copy of an overlay (trying some fancy plotting with transparent underthreshold areas of a voume).

I'm using fsleyes 0.34.2 installed through pypi (no virtualenv) on Ubuntu 20.04.1

**Comment by pauldmccarthy** [comment]
It looks like the code is assuming that all loaded overlays exist on disk, so it is not coping with the fact that your copy is not associated with a file.

 If you save your copy to a file, it should work. What I might do is update the code so that a warning is displayed if you try to generate a command line for a scene which contains overlays that are saved/associated with a file..

**Comment by smoia** [comment]
That sounds good, thanks!
You can close the issue if you don't need it!

**Comment by pauldmccarthy** [comment]
I've changed FSLeyes so that now a warning should be displayed when the show command line for scene option is selected with in-memory-only overlays displayed. Feel free to re-open this issue if you still experience problems
