### ISSUE TITLE
fsleyes fails to execute due to explicit dependency check

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#7]
Are you sure it won't work with a newer pillow?

```
chymera@zenhost ~ $ fsleyes 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/fsleyes", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Pillow<5.0,>=3.2.0' distribution was not found and is required by fsleyes
chymera@zenhost ~ $ eix -e pillow
[I] dev-python/pillow
     Available versions:  3.4.2-r1 4.3.0-r2 (~)4.3.0-r3 (~)5.2.0 {doc examples imagequant jpeg jpeg2k lcms qt5 test tiff tk truetype webp zlib PYTHON_TARGETS="pypy python2_7 python3_4 python3_5 python3_6 python3_7"}
     Installed versions:  5.2.0(22:35:12 14/09/18)(jpeg lcms tiff truetype zlib -doc -examples -imagequant -jpeg2k -test -tk -webp PYTHON_TARGETS="python2_7 python3_6 -pypy -python3_5 -python3_7")
     Homepage:            https://python-pillow.org/
     Description:         Python Imaging Library (fork)
```

Do you really want to do explicit dependency checking? It can lead to plenty of artificial failures, especially if you put upper bounds on the package versions.

**Comment by pauldmccarthy** [comment]
I'll check this for the next version, but this is unlikely to be before November-December.

**Comment by TheChymera** [comment]
I ran the test suite with both `3.4.2-r1` and `5.2.0`, and I did not get any additional errors. Also fsleyes seems to work well with pillow `5.2.0`.

**Comment by TheChymera** [comment]
I have patched this in the Gentoo Linux package distribution, it would be cool if the next release also removed the constraint, so it works directly from source :)
